"""Generate shared build inputs from one checked-in manifest; --check never writes."""
import argparse
import json
import re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def outputs(root=ROOT):
    doc=json.loads((root/'scripts/build_manifest.json').read_text(encoding='utf-8'))
    if doc.get('schema')!=1: raise ValueError('unsupported build manifest schema')
    release=doc['release']
    if not re.fullmatch(r'v\d+\.\d+\.\d+-rc\d+',release['version']) or release['stamp']!='wsm-'+release['version']:
        raise ValueError('inconsistent release identity')
    if not isinstance(release['versionCode'],int) or release['versionCode']<=0: raise ValueError('invalid versionCode')
    sources=doc['engineSources'];fixtures=doc['fixtures']
    if not sources or len(sources)!=len(set(sources)) or not fixtures: raise ValueError('empty/duplicate build inventory')
    for name in sources+[s for values in fixtures.values() for s in values]:
        if not re.fullmatch(r'[a-z0-9_]+\.cpp',name) or not (root/'jni'/name).is_file(): raise ValueError('invalid source: '+name)
    for name in fixtures:
        if not re.fullmatch(r'[a-z0-9_]+',name) or not (root/'tests'/(name+'_test.cpp')).is_file(): raise ValueError('invalid fixture: '+name)
    expected={p.stem[:-5] for p in (root/'tests').glob('*_test.cpp')}
    if set(fixtures)!=expected: raise ValueError('manifest must register every native fixture')
    cmake='# Generated by scripts/generate_build_config.py; edit build_manifest.json.\n'
    cmake+='set(WSM_ENGINE_SOURCES '+' '.join(sources)+')\n'
    cmake+='set(WSM_UNIT_NAMES '+' '.join(fixtures)+')\n'
    for name,deps in fixtures.items(): cmake+='set(WSM_UNIT_'+name+'_SOURCES '+' '.join(deps)+')\n'
    mk='# Generated by scripts/generate_build_config.py; edit build_manifest.json.\nWSM_ENGINE_SOURCES := '+' '.join(sources)+'\n'
    header='#pragma once\n// Generated release identity.\n#define WSM_BUILD_STAMP "'+release['stamp']+'"\n'
    prop=(root/'module-template/module.prop').read_text(encoding='utf-8')
    prop=re.sub(r'^version=.*$', 'version='+release['version'],prop,flags=re.M)
    prop=re.sub(r'^versionCode=.*$', 'versionCode='+str(release['versionCode']),prop,flags=re.M)
    return {'jni/build_sources.cmake':cmake,'jni/build_sources.mk':mk,'jni/wsm_version.h':header,'module-template/module.prop':prop}

def generate(check=False):
    for name,content in outputs().items():
        path=ROOT/name
        if check:
            if not path.is_file() or path.read_text(encoding='utf-8')!=content: raise ValueError('generated build input differs: '+name)
        elif not path.is_file() or path.read_text(encoding='utf-8')!=content:
            path.write_text(content,encoding='utf-8',newline='\n')

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true')
    generate(parser.parse_args().check)
    print('Shared build manifest: PASS')
