# Generated by scripts/generate_build_config.py; edit build_manifest.json.
WSM_ENGINE_SOURCES := engine.cpp il2cpp_resolver.cpp aob_scanner.cpp hybrid_resolver.cpp feature_flags.cpp dispatcher.cpp payload_worker.cpp
